### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by grodino** [pebble/pybluetooth#3]
Hi pebblers !

I'm trying to get pybluetooth running on my pc but when pip tries to instal scapy, it fails : 
`Could not find a version that satisfies the requirement scapy==2.3.2.dev0 (from pybluetooth==0.0.2) (from versions: 2.2.0-dev.linux-x86_64, 2.2.0.dev0, 2.3.1, 2.3.2)
No matching distribution found for scapy==2.3.2.dev0 (from pybluetooth==0.0.2)`

I tried to modify the setup.py to remove the dev requirement and replace it by the last version (2.3.2) but it also fails, trying to execute a UNIX command : 

```
Collecting scapy
  Using cached scapy-2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\agodi\AppData\Local\Temp\pip-build-yal0ouik\scapy\setup.py", line 35
        os.chmod(fname,0755)
                          ^
    SyntaxError: invalid token

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\agodi\AppData\Local\Temp\pip-build-yal0ouik\scapy\

```

Thank you for your help,
Augustin

**Comment by grodino** [comment]
Resolved it by modifying the setup.py

**Comment by martijnthe** [comment]
Hi Augustin,

This project depends on scapy and new features that aren't part of an official release yet, though they have been merged into master.

I'd recommend installing scapy from our own clone: https://github.com/pebble/scapy

Hope that helps.

Let me know if it works on Windows. I haven't tested it at all on Windows yet.

Martijn

**Comment by grodino** [comment]
Thank you for your answer,

I did install scapy from your clone and just added a condition before `os.chmod(fname,0755)`

```
if os.name is 'posix':
    os.chmod(fname,0755)
```

It seems to work now.
